#############################################################################
# Makefile for building: emui_test.app/Contents/MacOS/emui_test
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  emui_test.pro
# Template: app
# Command: /Users/dhr/Qt/5.12.0/clang_64/bin/qmake -o emui_test.xcodeproj/project.pbxproj emui_test.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/dhr/Qt/5.12.0/clang_64/bin/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/Users/dhr/LANL/git/github/cinemascience/cinema_scope"'
INCPATH       = -I. -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtTest.framework/Headers -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/dhr/Qt/5.12.0/clang_64/mkspecs/macx-clang -F/Users/dhr/Qt/5.12.0/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

check: first
	/Users/dhr/LANL/git/github/cinemascience/cinema_scope/target_wrapper.sh $(TESTRUNNER) ./$(QMAKE_TARGET).app/Contents/MacOS/$(QMAKE_TARGET) $(TESTARGS)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

benchmark: first

compilers: moc_predefs.h EmuTest.moc
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/dhr/Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Users/dhr/Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all: EmuTest.moc
compiler_moc_source_clean:
	-$(DEL_FILE) EmuTest.moc
EmuTest.moc: /Users/dhr/Qt/5.12.0/clang_64/lib/QtTest.framework/Headers/QtTest \
		/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		src/EmuDatabase.h \
		/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QVector \
		src/EmuResult.h \
		src/EmuTest.cpp \
		moc_predefs.h \
		/Users/dhr/Qt/5.12.0/clang_64/bin/moc
	/Users/dhr/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/dhr/LANL/git/github/cinemascience/cinema_scope/moc_predefs.h -I/Users/dhr/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/dhr/LANL/git/github/cinemascience/cinema_scope -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtTest.framework/Headers -I/Users/dhr/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/dhr/Qt/5.12.0/clang_64/lib src/EmuTest.cpp -o EmuTest.moc

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_source_clean 

