#!/usr/bin/env python

from PIL import Image, ImageDraw, ImageFont
import itertools
import os

database = "test.cdb"
font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 40)
os.mkdir(database)
os.chdir(database)

# a = [[10,11,12,13],[20,21,22,23],[30,31,32,33],[40,41,42,43]]
# names = "one,two,three,four,FILE"
parameters = [[10,11,12,13],[20,21,22,23]]
names      = "phi,theta,FILE"
allParams  = list(itertools.product(*parameters))

os.mkdir("image")
with open("data.csv", "w") as csvfile:
    csvfile.write(names + "\n")
    row = ""

    # do this for all sets of parameters
    for pSet in allParams:
        curdir = "image"
        row = ""
        notfirst = 0

        # each parameter becomes a directory
        for d in pSet:
            if (notfirst):
                row += ","
            else:
                notfirst = 1
            curdir = os.path.join(curdir, str(d))
            row += str(d)
            if not os.path.exists(curdir):
                os.mkdir(curdir)

        # now create an image file for that directory
        imgfile = os.path.join(curdir, "image.png")
        csvfile.write(row + "," + imgfile + "\n")
        img = Image.new('RGB', (800,400), (0,0,0))
        d = ImageDraw.Draw(img)
        d.text((10,10), imgfile, font=font, fill=(255,255,255))
        img.save(imgfile, "PNG")

