#!/usr/bin/env python

from PIL import Image, ImageDraw, ImageFont
import itertools
import os

database = "test.cdb"
font = ImageFont.truetype("../docs/font/prociono-master/Prociono.otf", 40)

os.mkdir(database)
os.chdir(database)

# large dataset 
# parameters = [  [10,11,12,13,14,15,16,17,18,19],
                # [20,21,22,23,24,25,26,27,28,29],
                # [30,31,32,33,34,35,36,37,38,39],
                # [40,41,42,43,44,45,46,47,48,49]]
# names      = "one,two,three,f four,FILE"
# small dataset
# simple, even spacing
# parameters = [[10,11,12,13],[20,21,22,23]]
# uneven spacing
# parameters = [[10.1,17.1,18.1,19.1,20.1,25.1,26.1,27.1,30.1],[20,21,22,23]]
# parameters = [[10.1,17.1,17.2,17.3,17.4,25.1,26.1,27.1,30.1],[20,21,22,23]]
# names      = "phi,theta,FILE"
# text
parameters = [[10,11,12,13],[20,21,22,23],["text_0","text_1","text_2","text_3"]]
names      = "phi,theta,name,FILE"
# parameters = [[10,11,12,13],[20,21,22,23]]
# names      = "phi,theta,FILE"
parameters = [[-180.1,180.1],[-90.1,90.1],[180,90],[-180,-90],["one","two"],["three","four"]] 
names      = "phi,theta,iphi,itheta,sphi,stheta,FILE"
allParams  = list(itertools.product(*parameters))

os.mkdir("image")
with open("data.csv", "w") as csvfile:
    csvfile.write(names + "\n")
    row = ""

    # do this for all sets of parameters
    for pSet in allParams:
        curdir = "image"
        row = ""
        notfirst = 0

        # each parameter becomes a directory
        for d in pSet:
            if (notfirst):
                row += ","
            else:
                notfirst = 1
            curdir = os.path.join(curdir, str(d))
            row += str(d)
            if not os.path.exists(curdir):
                os.mkdir(curdir)

        # now create an image file for that directory
        imgfile = os.path.join(curdir, "image.png")
        csvfile.write(row + "," + imgfile + "\n")
        img = Image.new('RGB', (1920,1080), (0,0,0))
        d = ImageDraw.Draw(img)
        d.text((10,20), imgfile, font=font, fill=(255,255,255))
        img.save(imgfile, "PNG")
