#! /Users/dhr/anaconda/envs/py36/bin/python

from PIL import Image, ImageDraw, ImageFont
import itertools
import os

database = "test.cdb"
font = ImageFont.truetype("Helvetica.ttc", 40)
os.mkdir(database)
os.chdir(database)

# a = [[10,11,12,13],[20,21,22,23],[30,31,32,33],[40,41,42,43]]
# names = "one,two,three,four,FILE"
a = [[10,11,12,13],[20,21,22,23]]
names = "phi,theta,FILE"
allLists = list(itertools.product(*a))

os.mkdir("image")
with open("data.csv", "w") as csvfile:
    csvfile.write(names + "\n")
    row = ""
    for l in allLists:
        curdir = "image"
        row = ""
        notfirst = 0
        for d in l:
            if (notfirst):
                row += ","
            else:
                notfirst = 1
            curdir = os.path.join(curdir, str(d))
            row += str(d)
            if not os.path.exists(curdir):
                os.mkdir(curdir)

        imgfile = os.path.join(curdir, "image.png")
        csvfile.write(row + "," + imgfile + "\n")
        img = Image.new('RGB', (800,400), (0,0,0))
        d = ImageDraw.Draw(img)
        d.text((10,10), imgfile, font=font, fill=(255,255,255))
        img.save(imgfile, "PNG")

