#!/bin/bash

QTBIN="/Users/dhr/Qt/QtIFW-3.0.6/bin"
BINARYCREATOR="$QTBIN/binarycreator"
DEPLOY="/Users/dhr/Qt/5.12.0/clang_64/bin/macdeployqt"
APP="CinemaScope.app"

echo "Cleaning packages/cinemascope/data ..."
rm -rf packages/cinemascope/data/$APP

echo "Copying current build ..."
cp -rf ../build/release/$APP packages/cinemascope/data

echo "Running mac delpoyment ..."
$DEPLOY packages/cinemascope/data/$APP

echo "Creating installer ..."
$BINARYCREATOR -t $QTBIN/installerbase -c config/config.xml -p packages CinemaScopeInstaller.dmg

echo "Cleaning packages/cinemascope/data ..."
rm -rf packages/cinemascope/data/$APP
